services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/logs
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    
volumes:
  mongo-data: